<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
Ly8gR2V0IGZpbGUgcGF0aCBmcm9tIHBpcGVsaW5lDQogICAgU3RyaW5nIGZpbGVQYXRoID0gbnVs
bDsNCiAgICBpZiAoY3Vyc29yLmZpcnN0KCJmaWxlUGF0aCIpKSB7DQogICAgICAgIGZpbGVQYXRo
ID0gKFN0cmluZykgY3Vyc29yLmdldFZhbHVlKCk7DQogICAgfQ0KICAgIA0KICAgIGlmIChmaWxl
UGF0aCA9PSBudWxsIHx8IGZpbGVQYXRoLmlzRW1wdHkoKSkgew0KICAgICAgICB0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiRmlsZSBwYXRoIGlzIG1pc3NpbmciKTsNCiAgICB9DQogICAgDQog
ICAgLy8gUmVhZCBmaWxlIGNvbnRlbnQNCiAgICBTdHJpbmcgY29udGVudCA9IG5ldyBTdHJpbmco
RmlsZXMucmVhZEFsbEJ5dGVzKFBhdGhzLmdldChmaWxlUGF0aCkpLCAiVVRGLTgiKTsNCiAgICAN
CiAgICAvLyBQdXQgY29udGVudCBpbnRvIHBpcGVsaW5lDQogICAgSURhdGFVdGlsLnB1dChjdXJz
b3IsICJmaWxlQ29udGVudCIsIGNvbnRlbnQpOw0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0K
ICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFcnJvciByZWFkaW5nIGZpbGU6ICIgKyBl
LmdldE1lc3NhZ2UoKSk7DQp9IGZpbmFsbHkgew0KICAgIGN1cnNvci5kZXN0cm95KCk7DQp9DQoN
Cg0KCQ==</value>
</Values>
